// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCChw3js2lsmuzJcYnU7D8HD0xGIeOVEbs',
    appId: '1:594899742468:web:b2de86c743df3ad1046a51',
    messagingSenderId: '594899742468',
    projectId: 'tetststst-a1360',
    authDomain: 'tetststst-a1360.firebaseapp.com',
    databaseURL: 'https://tetststst-a1360-default-rtdb.firebaseio.com',
    storageBucket: 'tetststst-a1360.appspot.com',
    measurementId: 'G-3KLQRC47S8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHKRu3i4gZrdhpKKuNNY33xtTfPF64IWg',
    appId: '1:594899742468:android:e71ca876f93bf949046a51',
    messagingSenderId: '594899742468',
    projectId: 'tetststst-a1360',
    databaseURL: 'https://tetststst-a1360-default-rtdb.firebaseio.com',
    storageBucket: 'tetststst-a1360.appspot.com',
  );
}
